sudo: false
language: python
python:
  - "3.5"
env:
  matrix:
    - TOX_ENV=py27-stdlib
    - TOX_ENV=py34-stdlib
    - TOX_ENV=py35-stdlib
    - TOX_ENV=py27-gevent
    - TOX_ENV=py34-gevent
    - TOX_ENV=py35-gevent
    - TOX_ENV=flake8
cache:
  pip: true
install:
  - "travis_retry pip install setuptools pip --upgrade"
  - "travis_retry pip install tox"
script:
  - tox -e $TOX_ENV --recreate
after_script:
  - cat .tox/$TOX_ENV/log/*.log
